### ISSUE TITLE
Android Studio freezes

### ISSUE THREAD

**Issue by fmatosqg** [galex/name-that-color-intellij-plugin#12]
After installing this plugin I noticed repeated freezes while typing code, waiting doesn't work.

After killing AS and reopening I also notice that the last few files edited were reverted, which adds to the severity of the problem.

Disabling the plugin made AS usable again.

Tried on AS 3.0.1 stable and 3.1 beta 4.

**Comment by galex** [comment]
Thanks, I'll check that.

**Comment by galex** [comment]
I can't reproduce this issue.
If you have more info I'll be happy to try again.
