### ISSUE TITLE
Add support for Android Studio 3.5 / IntelliJ IDEA 2019.1

### ISSUE THREAD

**Issue by DeKaN** [galex/name-that-color-intellij-plugin#15]
Android Studio 3.5 based on IntelliJ IDEA 2019.1 (191.6183.*) released at March 2019

The current version works only if I manually change restriction in `META-INF/plugin.xml`

**Comment by sagarrishabh** [comment]
Please provide support for Android Studio 3.5. It's too tough to decide names for the colours 😅.

**Comment by galex** [comment]
Will update as soon as possible!

**Comment by sagarrishabh** [comment]
@galex Thanks :)

**Comment by DeKaN** [comment]
@galex Android Studio 3.6 based on 191.7141. and it allows to use version for 3.5

**Comment by santalu** [comment]
Hey @galex. I hope you're doing well.  Could we please know if there's any update on this? 
Thank you for the great plugin.

**Comment by galex** [comment]
@sagarrishabh @DeKaN @santalu Hello, Sorry for the long delay. I've submitted an updated plugin to JetBrains. It should make it to the Plugins Repository next week.
