### ISSUE TITLE
unable to install Android Studio 4.0

### ISSUE THREAD

**Issue by mortuzahossain** [galex/name-that-color-intellij-plugin#21]
Android Studio 4.0
Build #AI-193.6911.18.40.6514223, built on May 20, 2020

**Comment by mortuzahossain** [comment]
I love your plugin and i am really very much used to it. After updating my android studio I am unable to find the plugin in my search and also when I am trying to install it by downloading it as zipping it gives me an error and I can't install. If you fix this issue I will be very grateful. Thanks in advance.

**Comment by galex** [comment]
Thank you for your patience, I've just pushed an update to Jetbrains, should be available in two days.

**Comment by mortuzahossain** [comment]
Thanks a lot for updating your plugin.
