### ISSUE TITLE
The latest version studio 4.1 cannot support this plugin

### ISSUE THREAD

**Issue by ttym** [galex/name-that-color-intellij-plugin#24]
When I updating the latest Android studio version 4.1,this plugin shows error for supportd only in intellij IDEA message in event log

could u just fix this issue?

**Comment by hormesiel** [comment]
I have the same problem since I updated AS to version 4.1.

![image](https://user-images.githubusercontent.com/1585006/96424064-7b1e1f80-11fa-11eb-8f69-75513a031ae2.png)

**Comment by BanHammerYKT** [comment]
Same problem with Android Studio 4.1 Build #AI-201.8743.12.41.6858069, built on September 24, 2020

**Comment by galex** [comment]
I will update it soon 👍

**Comment by iamarjun** [comment]
+1

**Comment by timtsj** [comment]
@galex ping

**Comment by lucaseron** [comment]
Is it currently working? My Android Studio keeps showing me this error...

**Comment by galex** [comment]
Didn't get to it yet, sorry. If you want to submit a PR I'd be happy to check it & publish.

**Comment by timtsj** [comment]
@galex hi, any news?

**Comment by timtsj** [comment]
maybe some one know online version like this plugin?
