### ISSUE TITLE
Not working with #AARRGGBB

### ISSUE THREAD

**Issue by aednlaxer** [galex/name-that-color-intellij-plugin#5]
Plugin is not showing autocomplete items for ARGB value.

Steps to reproduce:
1. Copy `#80FAFAFA` (alabaster, 50% alpha) to the clipboard
2. Try to use plugin in the `colors.xml` -> `No suggestions` message is displayed

Expected behavior: plugin autocompletes to 
```xml
<color name="alabaster_50">#80fafafa</color>
```
where `50` is a transparency value.

**Comment by galex** [comment]
Great idea for adding the alpha in the name itself!

**Comment by galex** [comment]
This went live today in version 1.2.0. Update your plugins in Android Studio!
