### ISSUE TITLE
Misleading color names

### ISSUE THREAD

**Issue by aednlaxer** [galex/name-that-color-intellij-plugin#7]
After fix for #5 and adding Material Design colors, one name can mean different colors:
* `#FFEBEE` gives `red_50` as per Material Design palette
* `#80FF0000` gives `red_50` as "red with 50% opacity"

Maybe it's better to use "red50" (no underscore) for Material Design colors, keep "red_50" for transparent colors.

Plugin version 1.2.0
Android Studio version 3.0.1

**Comment by galex** [comment]
You are totally right, it is confusing as two colors could get the same name meaning different things.
We need a better way to differentiate the alpha from the name of the color. 
Your solution could work for some of the names of the [material colors](https://github.com/galex/name-that-color-intellij-plugin/blob/master/namethatcolor/src/main/kotlin/il/co/galex/namethatcolor/core/util/MaterialColors.kt):
- red_50_50 would become red50_50
- red_A700_60 would become redA700_60

But what about **light_blue_A700_80** for example, should it be:

- light_blueA700_80
- lightblueA700_80
- lightBlueA700_80

I think the prettiest would be camelCase but that's not really the convention out there.

What do you think @aednlaxer ?

**Comment by aednlaxer** [comment]
It's a matter of taste, I guess. I'm fine with anything, but second option is less readable than the others

**Comment by galex** [comment]
What about keeping the underscore and just adding "_alpha_50" at the end?
It makes the names long but easier to understand without dropping the convention. Using our examples:
- red_50_50 would become red_50_alpha_50
- red_A700_60 would become red_A700_alpha_60
- light_blue_A700_80 would become light_blue_A700_alpha_80

Better right?

**Comment by aednlaxer** [comment]
Yeah, makes sense
