### ISSUE TITLE
Plugin doesn't work with lowercase values

### ISSUE THREAD

**Issue by aednlaxer** [galex/name-that-color-intellij-plugin#8]
Plugin doesn't work with colors written in lowercase:
* `#fafafa` gives no suggestions but `#FAFAFA` gives `alabaster` and `grey_50` 
* `#2a000000` gives no suggestions but `#2A000000` gives `black_16`

Plugin version 1.2.0
Android Studio version 3.0.1

**Comment by galex** [comment]
This was fixed in 1.3.0 and uploaded to Jetbrains and is waiting for approval (it takes two or three days).
